# Generated by Django 5.1.6 on 2025-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(default=None, max_length=500),
        ),
    ]
