# Generated by Django 5.1.6 on 2025-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_video_project_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
